// <auto-generated />
namespace EmployeeManagement.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class inititalcreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inititalcreate));
        
        string IMigrationMetadata.Id
        {
            get { return "202512120702229_initital create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
